Feature: select quantities of equipment

As any type of vendor for the RMSI
I want to be able to select quantities of rental equipment
So that I can rent multiple pieces of equipment if needed

Scenario: Selecting equipment on food vendor page
    Given I am on the food page
    And I select "one" from "6' Table ($10)"
    Then the "6' Table ($10)" field should contain "one"
    Then I select "two" from "6' Table ($10)"
    Then the "6' Table ($10)" field should contain "two"
    Then I select "three" from "6' Table ($10)"
    Then the "6' Table ($10)" field should contain "three"
    Then I select "zero" from "6' Table ($10)"
    Then the "6' Table ($10)" field should contain "zero"    
    Then I select "one" from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field should contain "one"
    Then I select "two" from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field should contain "two"
    Then I select "three" from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field should contain "three"
    Then I select "zero" from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field should contain "zero"        
    Then I select "one" from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field should contain "one"
    Then I select "two" from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field should contain "two"
    Then I select "three" from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field should contain "three"
    Then I select "zero" from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field should contain "zero"    
    Then I select "one" from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field should contain "one"
    Then I select "two" from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field should contain "two"
    Then I select "three" from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field should contain "three"
    Then I select "zero" from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field should contain "zero"        
    
Scenario: Selecting equipment on retail page
    Given I am on the retail page
    And I select "one" from "6' Table ($10)"
    Then the "6' Table ($10)" field should contain "one"
    Then I select "two" from "6' Table ($10)"
    Then the "6' Table ($10)" field should contain "two"
    Then I select "three" from "6' Table ($10)"
    Then the "6' Table ($10)" field should contain "three"
    Then I select "zero" from "6' Table ($10)"
    Then the "6' Table ($10)" field should contain "zero"    
    Then I select "one" from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field should contain "one"
    Then I select "two" from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field should contain "two"
    Then I select "three" from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field should contain "three"
    Then I select "zero" from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field should contain "zero"        
    Then I select "one" from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field should contain "one"
    Then I select "two" from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field should contain "two"
    Then I select "three" from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field should contain "three"
    Then I select "zero" from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field should contain "zero"    
    Then I select "one" from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field should contain "one"
    Then I select "two" from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field should contain "two"
    Then I select "three" from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field should contain "three"
    Then I select "zero" from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field should contain "zero"      
    
Scenario: Selecting equipment on nonprofit page
    Given I am on the nonprofit page
    And I select "one" from "6' Table ($10)"
    Then the "6' Table ($10)" field should contain "one"
    Then I select "two" from "6' Table ($10)"
    Then the "6' Table ($10)" field should contain "two"
    Then I select "three" from "6' Table ($10)"
    Then the "6' Table ($10)" field should contain "three"
    Then I select "zero" from "6' Table ($10)"
    Then the "6' Table ($10)" field should contain "zero"    
    Then I select "one" from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field should contain "one"
    Then I select "two" from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field should contain "two"
    Then I select "three" from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field should contain "three"
    Then I select "zero" from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field should contain "zero"        
    Then I select "one" from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field should contain "one"
    Then I select "two" from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field should contain "two"
    Then I select "three" from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field should contain "three"
    Then I select "zero" from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field should contain "zero"    
    Then I select "one" from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field should contain "one"
    Then I select "two" from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field should contain "two"
    Then I select "three" from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field should contain "three"
    Then I select "zero" from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field should contain "zero"      
    
Scenario: Selecting equipment on commercial info page
    Given I am on the commercialInfo page
    And I select "one" from "6' Table ($10)"
    Then the "6' Table ($10)" field should contain "one"
    Then I select "two" from "6' Table ($10)"
    Then the "6' Table ($10)" field should contain "two"
    Then I select "three" from "6' Table ($10)"
    Then the "6' Table ($10)" field should contain "three"
    Then I select "zero" from "6' Table ($10)"
    Then the "6' Table ($10)" field should contain "zero"    
    Then I select "one" from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field should contain "one"
    Then I select "two" from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field should contain "two"
    Then I select "three" from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field should contain "three"
    Then I select "zero" from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field should contain "zero"        
    Then I select "one" from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field should contain "one"
    Then I select "two" from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field should contain "two"
    Then I select "three" from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field should contain "three"
    Then I select "zero" from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field should contain "zero"    
    Then I select "one" from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field should contain "one"
    Then I select "two" from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field should contain "two"
    Then I select "three" from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field should contain "three"
    Then I select "zero" from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field should contain "zero"          
