Feature: select quantities of equipment

As any type of vendor for the RMSI
I want to be able to select quantities of rental equipment
So that I can rent multiple pieces of equipment if needed

Scenario: Selecting equipment on food vendor page
    Given I am on the food page
    And I select "1" for equipment rentals from "6' Table ($10)"
    Then the "6' Table ($10)" field for equipment rentals should contain "1"
    Then I select "2" for equipment rentals from "6' Table ($10)"
    Then the "6' Table ($10)" field for equipment rentals should contain "2"
    Then I select "3" for equipment rentals from "6' Table ($10)"
    Then the "6' Table ($10)" field for equipment rentals should contain "3"
    Then I select "0" for equipment rentals from "6' Table ($10)"
    Then the "6' Table ($10)" field for equipment rentals should contain "0"    
    Then I select "1" for equipment rentals from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field for equipment rentals should contain "1"
    Then I select "2" for equipment rentals from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field for equipment rentals should contain "2"
    Then I select "3" for equipment rentals from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field for equipment rentals should contain "3"
    Then I select "0" for equipment rentals from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field for equipment rentals should contain "0"        
    Then I select "1" for equipment rentals from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field for equipment rentals should contain "1"
    Then I select "2" for equipment rentals from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field for equipment rentals should contain "2"
    Then I select "3" for equipment rentals from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field for equipment rentals should contain "3"
    Then I select "0" for equipment rentals from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field for equipment rentals should contain "0"    
    Then I select "1" for equipment rentals from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field for equipment rentals should contain "1"
    Then I select "2" for equipment rentals from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field for equipment rentals should contain "2"
    Then I select "3" for equipment rentals from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field for equipment rentals should contain "3"
    Then I select "0" for equipment rentals from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field for equipment rentals should contain "0"        
    
Scenario: Selecting equipment on retail page
    Given I am on the retail page
    And I select "1" for equipment rentals from "6' Table ($10)"
    Then the "6' Table ($10)" field for equipment rentals should contain "1"
    Then I select "2" for equipment rentals from "6' Table ($10)"
    Then the "6' Table ($10)" field for equipment rentals should contain "2"
    Then I select "3" for equipment rentals from "6' Table ($10)"
    Then the "6' Table ($10)" field for equipment rentals should contain "3"
    Then I select "0" for equipment rentals from "6' Table ($10)"
    Then the "6' Table ($10)" field for equipment rentals should contain "0"    
    Then I select "1" for equipment rentals from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field for equipment rentals should contain "1"
    Then I select "2" for equipment rentals from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field for equipment rentals should contain "2"
    Then I select "3" for equipment rentals from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field for equipment rentals should contain "3"
    Then I select "0" for equipment rentals from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field for equipment rentals should contain "0"        
    Then I select "1" for equipment rentals from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field for equipment rentals should contain "1"
    Then I select "2" for equipment rentals from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field for equipment rentals should contain "2"
    Then I select "3" for equipment rentals from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field for equipment rentals should contain "3"
    Then I select "0" for equipment rentals from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field for equipment rentals should contain "0"    
    Then I select "1" for equipment rentals from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field for equipment rentals should contain "1"
    Then I select "2" for equipment rentals from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field for equipment rentals should contain "2"
    Then I select "3" for equipment rentals from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field for equipment rentals should contain "3"
    Then I select "0" for equipment rentals from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field for equipment rentals should contain "0"        
    
Scenario: Selecting equipment on nonprofit page
    Given I am on the nonprofit page
    And I select "1" for equipment rentals from "6' Table ($10)"
    Then the "6' Table ($10)" field for equipment rentals should contain "1"
    Then I select "2" for equipment rentals from "6' Table ($10)"
    Then the "6' Table ($10)" field for equipment rentals should contain "2"
    Then I select "3" for equipment rentals from "6' Table ($10)"
    Then the "6' Table ($10)" field for equipment rentals should contain "3"
    Then I select "0" for equipment rentals from "6' Table ($10)"
    Then the "6' Table ($10)" field for equipment rentals should contain "0"    
    Then I select "1" for equipment rentals from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field for equipment rentals should contain "1"
    Then I select "2" for equipment rentals from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field for equipment rentals should contain "2"
    Then I select "3" for equipment rentals from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field for equipment rentals should contain "3"
    Then I select "0" for equipment rentals from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field for equipment rentals should contain "0"        
    Then I select "1" for equipment rentals from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field for equipment rentals should contain "1"
    Then I select "2" for equipment rentals from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field for equipment rentals should contain "2"
    Then I select "3" for equipment rentals from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field for equipment rentals should contain "3"
    Then I select "0" for equipment rentals from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field for equipment rentals should contain "0"    
    Then I select "1" for equipment rentals from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field for equipment rentals should contain "1"
    Then I select "2" for equipment rentals from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field for equipment rentals should contain "2"
    Then I select "3" for equipment rentals from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field for equipment rentals should contain "3"
    Then I select "0" for equipment rentals from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field for equipment rentals should contain "0"      
    
Scenario: Selecting equipment on commercial info page
    Given I am on the commercialInfo page
    And I select "1" for equipment rentals from "6' Table ($10)"
    Then the "6' Table ($10)" field for equipment rentals should contain "1"
    Then I select "2" for equipment rentals from "6' Table ($10)"
    Then the "6' Table ($10)" field for equipment rentals should contain "2"
    Then I select "3" for equipment rentals from "6' Table ($10)"
    Then the "6' Table ($10)" field for equipment rentals should contain "3"
    Then I select "0" for equipment rentals from "6' Table ($10)"
    Then the "6' Table ($10)" field for equipment rentals should contain "0"    
    Then I select "1" for equipment rentals from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field for equipment rentals should contain "1"
    Then I select "2" for equipment rentals from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field for equipment rentals should contain "2"
    Then I select "3" for equipment rentals from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field for equipment rentals should contain "3"
    Then I select "0" for equipment rentals from "Folding Chair ($5)"
    Then the "Folding Chair ($5)" field for equipment rentals should contain "0"        
    Then I select "1" for equipment rentals from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field for equipment rentals should contain "1"
    Then I select "2" for equipment rentals from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field for equipment rentals should contain "2"
    Then I select "3" for equipment rentals from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field for equipment rentals should contain "3"
    Then I select "0" for equipment rentals from "11' Market Umbrella ($50)"
    Then the "11' Market Umbrella ($50)" field for equipment rentals should contain "0"    
    Then I select "1" for equipment rentals from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field for equipment rentals should contain "1"
    Then I select "2" for equipment rentals from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field for equipment rentals should contain "2"
    Then I select "3" for equipment rentals from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field for equipment rentals should contain "3"
    Then I select "0" for equipment rentals from "10'x10' Food Service Tent ($110)"
    Then the "10'x10' Food Service Tent ($110)" field for equipment rentals should contain "0"           
